In [ ]:
import pandas as pd
import numpy as np
from math import pi

from bokeh.io import show, output_notebook
from bokeh.models import BasicTicker, ColorBar, LinearColorMapper, PrintfTickFormatter
from bokeh.plotting import figure

In [ ]:
data = pd.read_feather(r'C:\Users\rsilva\Downloads\saida\levels\RFeye002310_210215_T055800-B_67_TId_110.fth')
data = data.iloc[:1000, :1000]

In [ ]:
data['index'] = pd.to_datetime(data['index']).dt.strftime("%d/%m/%Y-%H:%M:%S")

In [ ]:
data.head()

,index,1530.0,1530.0387495929665,1530.077499185933,1530.1162487788995,1530.1549983718658,1530.1937479648323,1530.2324975577988,1530.2712471507652,1530.3099967437317,...,1568.3233474438293,1568.3620970367958,1568.4008466297623,1568.4395962227288,1568.4783458156953,1568.5170954086616,1568.555845001628,1568.5945945945946,1568.633344187561,1568.6720937805276
0,15/02/2021-05:59:00,-113.5,-118.5,-124.5,-122.0,-122.5,-120.5,-114.0,-112.5,-114.0,...,-109.5,-111.0,-113.0,-111.5,-110.5,-114.5,-112.0,-115.0,-120.5,-115.0
1,15/02/2021-06:00:00,-118.0,-118.5,-119.0,-109.5,-116.5,-116.0,-113.0,-111.5,-112.5,...,-111.0,-115.5,-120.0,-124.5,-121.5,-123.5,-124.0,-127.0,-119.0,-115.0
2,15/02/2021-06:01:00,-122.0,-114.5,-114.0,-114.5,-115.0,-114.5,-115.0,-117.5,-113.5,...,-110.0,-111.5,-112.0,-114.0,-116.0,-119.0,-117.0,-114.0,-117.0,-122.5
3,15/02/2021-06:02:00,-121.5,-117.0,-113.5,-109.5,-111.5,-114.0,-116.0,-118.5,-117.0,...,-114.5,-116.0,-119.5,-116.5,-114.0,-111.5,-111.0,-115.0,-115.0,-116.0
4,15/02/2021-06:03:00,-115.5,-116.0,-115.5,-117.5,-111.5,-112.0,-122.0,-120.5,-112.0,...,-113.5,-110.0,-110.5,-110.5,-114.0,-119.5,-119.0,-117.0,-113.0,-111.5

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="white")

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(16, 12))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(-200, -50, as_cmap=True)

#cmap = sns.color_palette("rocket", as_cmap=True)


# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(data.set_index('index'), cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})

In [ ]:
data = data.set_index('index')
data.columns.name = "Frequencies"
data.index.name = "Time"
data.head()

Frequencies,1530.0,1530.0387495929665,1530.077499185933,1530.1162487788995,1530.1549983718658,1530.1937479648323,1530.2324975577988,1530.2712471507652,1530.3099967437317,1530.3487463366982,...,1568.3233474438293,1568.3620970367958,1568.4008466297623,1568.4395962227288,1568.4783458156953,1568.5170954086616,1568.555845001628,1568.5945945945946,1568.633344187561,1568.6720937805276
Time,,,,,,,,,,,,,,,,,,,,,
15/02/2021-05:59:00,-113.5,-118.5,-124.5,-122.0,-122.5,-120.5,-114.0,-112.5,-114.0,-113.0,...,-109.5,-111.0,-113.0,-111.5,-110.5,-114.5,-112.0,-115.0,-120.5,-115.0
15/02/2021-06:00:00,-118.0,-118.5,-119.0,-109.5,-116.5,-116.0,-113.0,-111.5,-112.5,-117.0,...,-111.0,-115.5,-120.0,-124.5,-121.5,-123.5,-124.0,-127.0,-119.0,-115.0
15/02/2021-06:01:00,-122.0,-114.5,-114.0,-114.5,-115.0,-114.5,-115.0,-117.5,-113.5,-114.0,...,-110.0,-111.5,-112.0,-114.0,-116.0,-119.0,-117.0,-114.0,-117.0,-122.5
15/02/2021-06:02:00,-121.5,-117.0,-113.5,-109.5,-111.5,-114.0,-116.0,-118.5,-117.0,-117.0,...,-114.5,-116.0,-119.5,-116.5,-114.0,-111.5,-111.0,-115.0,-115.0,-116.0
15/02/2021-06:03:00,-115.5,-116.0,-115.5,-117.5,-111.5,-112.0,-122.0,-120.5,-112.0,-109.5,...,-113.5,-110.0,-110.5,-110.5,-114.0,-119.5,-119.0,-117.0,-113.0,-111.5

In [ ]:
df = pd.DataFrame(data.stack(), columns=['Levels']).reset_index()

In [ ]:
df.tail()

                       Time         Frequencies  Levels
998995  15/02/2021-22:38:00  1568.5170954086616  -118.0
998996  15/02/2021-22:38:00   1568.555845001628  -118.5
998997  15/02/2021-22:38:00  1568.5945945945946  -111.5
998998  15/02/2021-22:38:00   1568.633344187561  -110.5
998999  15/02/2021-22:38:00  1568.6720937805276  -110.0

In [ ]:
time = data.index.values
frequencies = data.columns.values

In [ ]:
len(time), len(frequencies)

(1000, 999)

In [ ]:
time = time[np.arange(0, 999)].tolist()
frequencies = frequencies[np.arange(0,999)].tolist()

In [ ]:
# this is the colormap from the original NYTimes plot
colors = ["#75968f", "#a5bab7", "#c9d9d3", "#e2e2e2", "#dfccce", "#ddb7b1", "#cc7878", "#933b41", "#550b1d"]
mapper = LinearColorMapper(palette=colors, low=df.Levels.min(), high=df.Levels.max())

TOOLS = "hover,save,pan,box_zoom,reset,wheel_zoom"

p = figure(title="Waterfall ({0} - {1})".format(time[0], time[-1]),
           x_range=frequencies, y_range=time,
           x_axis_label = 'Frequencies',
           y_axis_label = 'Timestamp',
           x_axis_location="above", plot_width=1920, plot_height=1080,
           tools=TOOLS, toolbar_location='below',
           tooltips=[('FrequÃªncia', '@Frequencies'), ('Tempo', '@Time'), ('NÃ­vel', '@Levels')])

p.grid.grid_line_color = None
p.axis.axis_line_color = None
p.axis.major_tick_line_color = None
p.axis.major_tick_line_color = None
p.axis.major_label_text_font_size = "0px"
p.axis.major_label_standoff = 0
p.xaxis.major_label_orientation = pi / 3

p.rect(x="Frequencies", 
       y="Time", 
       width=1,
       height=1, 
       source=df,
       fill_color={'field': 'Levels', 'transform': mapper}, 
       line_color=None)



color_bar = ColorBar(color_mapper=mapper, major_label_text_font_size="10px",
                 ticker=BasicTicker(desired_num_ticks=len(colors)),
                 formatter=PrintfTickFormatter(format="%ddBm"),
                 label_standoff=6, border_line_color=None)

p.add_layout(color_bar, 'right')

show(p)      # show the plot