In [ ]:
import pandas as pd
from math import pi

from bokeh.io import show
from bokeh.models import BasicTicker, ColorBar, LinearColorMapper, PrintfTickFormatter
from bokeh.plotting import figure
from bokeh.sampledata.unemployment1948 import data

data['Year'] = data['Year'].astype(str)
data = data.set_index('Year')
data.drop('Annual', axis=1, inplace=True)
data.columns.name = 'Month'

years = list(data.index)
months = list(data.columns)

# reshape to 1D array or rates with a month and year for each row.
df = pd.DataFrame(data.stack(), columns=['rate']).reset_index()

In [ ]:
data = pd.read_feather(r'C:\Users\rsilva\Downloads\saida\levels\rfeye002092_210208_T202310_CRFSBINv.5.bin-B_67_TId_20.fth')
data = data.iloc[:1000, :1000]

In [ ]:
data['index'] = pd.to_datetime(data['index']).dt.strftime("%d/%m/%Y-%H:%M:%S")

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="white")

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(16, 12))

# Generate a custom diverging colormap
#cmap = sns.diverging_palette(-200, -50, as_cmap=True)

cmap = sns.color_palette("rocket", as_cmap=True)


# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(data.set_index('index'), cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})

In [ ]:
data = data.set_index('index')
data.columns.name = "Frequencies"
data.index.name = "Time"
data.head()

Frequencies,76.0,76.00390672689538,76.00781345379075,76.01172018068613,76.01562690758149,76.01953363447687,76.02344036137224,76.02734708826762,76.03125381516298,76.03516054205836,...,79.86375289952387,79.86765962641924,79.87156635331462,79.87547308020999,79.87937980710537,79.88328653400073,79.88719326089611,79.89109998779148,79.89500671468686,79.89891344158222
Time,,,,,,,,,,,,,,,,,,,,,
08/02/2021-20:23:10,-117.5,-113.0,-111.5,-110.0,-111.0,-114.5,-115.0,-110.0,-111.0,-113.0,...,-121.0,-121.5,-120.5,-126.0,-117.5,-113.5,-112.0,-109.5,-114.0,-118.5
08/02/2021-20:23:11,-113.5,-114.5,-111.0,-107.0,-111.0,-116.0,-118.0,-113.0,-109.5,-111.0,...,-112.5,-112.0,-117.5,-121.0,-120.5,-116.0,-117.0,-120.5,-115.5,-118.0
08/02/2021-20:23:11,-109.5,-111.5,-114.0,-116.0,-116.0,-117.0,-115.5,-116.5,-115.0,-115.0,...,-117.5,-109.0,-108.0,-111.0,-118.0,-116.5,-116.0,-116.5,-117.5,-119.0
08/02/2021-20:23:12,-120.5,-118.5,-125.0,-111.5,-115.5,-118.5,-121.5,-115.0,-108.5,-109.5,...,-108.5,-110.0,-112.5,-117.0,-116.0,-111.5,-111.0,-114.0,-116.5,-118.0
08/02/2021-20:23:12,-118.0,-117.5,-111.0,-110.5,-117.0,-116.0,-112.0,-109.0,-109.5,-113.0,...,-123.5,-119.5,-113.5,-114.5,-116.5,-115.5,-117.0,-118.0,-114.5,-111.5

In [ ]:
df = pd.DataFrame(data.stack(), columns=['Levels']).reset_index()

In [ ]:
df.head()

                  Time        Frequencies  Levels
0  08/02/2021-20:23:10               76.0  -117.5
1  08/02/2021-20:23:10  76.00390672689538  -113.0
2  08/02/2021-20:23:10  76.00781345379075  -111.5
3  08/02/2021-20:23:10  76.01172018068613  -110.0
4  08/02/2021-20:23:10  76.01562690758149  -111.0

In [ ]:
time = data.index.tolist()
frequencies = data.columns.tolist()

In [ ]:
# this is the colormap from the original NYTimes plot
colors = ["#75968f", "#a5bab7", "#c9d9d3", "#e2e2e2", "#dfccce", "#ddb7b1", "#cc7878", "#933b41", "#550b1d"]
mapper = LinearColorMapper(palette=colors, low=df.Levels.min(), high=df.Levels.max())

TOOLS = "hover,save,pan,box_zoom,reset,wheel_zoom"

p = figure(title="Waterfall ({0} - {1})".format(time[0], time[-1]),
           x_range=frequencies, y_range=list(set(time)),
           x_axis_location="above", plot_width=1280, plot_height=720,
           tools=TOOLS, toolbar_location='below',
           tooltips=[('FrequÃªncia', '@Frequencies'), ('Tempo', '@Time'), ('NÃ­vel', '@Levels')])

p.grid.grid_line_color = None
p.axis.axis_line_color = None
p.axis.major_tick_line_color = None
p.axis.major_label_text_font_size = "7px"
p.axis.major_label_standoff = 0
p.xaxis.major_label_orientation = pi / 3

p.rect(x="Frequencies", 
       y="Time", 
       width=1,
       height=1, 
       source=df,
       fill_color={'field': 'Levels', 'transform': mapper}, 
       line_color=None)

color_bar = ColorBar(color_mapper=mapper, major_label_text_font_size="7px",
                 ticker=BasicTicker(desired_num_ticks=len(colors)),
                 formatter=PrintfTickFormatter(format="%ddBm"),
                 label_standoff=6, border_line_color=None)

p.add_layout(color_bar, 'right')

show(p)      # show the plot